# Pratique Numpy

# Tableau

In [2]:
#creation de tableau 1D
import numpy as np
taba=np.array([0,1,2,3,4])
print(taba)

#dimension
print(taba.ndim)

#shape
print(taba.shape)

#longueur
print(len(taba))


[0 1 2 3 4]
1
(5,)
5


In [ ]:
#Tableau 2D ou matrice
tabb=np.array([[0,1,2],[3,4,5]])
print(tabb)

print(tabb.ndim)
print(tabb.shape)

#longeuur de la premiere dimension
print(len(tabb))

In [3]:

#creation avec generator function, debut, fin exclusive, increment
rana=np.arange(5)
print(rana)

ranb=np.arange(0,5,2)
print(ranb)

[0 1 2 3 4]
[0 2 4]


# Matrices

In [ ]:
#Matrices usuelles
#Creation de matrice avec tous les elements egaux à 1.
i1=np.ones((4,4))
print(i1)
print("="*20)
#zeros
#Creation de matrice avec tous les elements egaux à  0.
i0=np.zeros((4,4))
print(i0)
print("="*20)
#eye ou  Creation de matrice avec tous les elements diagonaux egaux à 1 matrice identite
iorth=np.eye(4)
print(iorth)
print("="*20)
#Creation de matrice avec tous les elements 0 sauf les elements diagonaux
idiag=np.diag(np.array([1,2,3,4]))
print(idiag)
print("="*20)


# Operations sur les matrices

In [1]:

#multiplication de matrices
import numpy as np
taba=np.array([[0,1,2],[3,4,5]])
tabb=np.array([[2,1],[5,4],[1,2]])

res=np.dot(taba,tabb)
 
print(res)

#multiplication de matrice par vecteur
import numpy as np
taba=np.array([[0,1,2],[3,4,5]])
vectb=np.array([[1],[2],[3]])

res=np.dot(taba,vectb)

print(res)


#transposition de matrice
import numpy as np
taba=np.array([[0,1,2],[3,4,5]])
res=taba.T

print(res)


#determinant dematrice
import numpy as np
taba=np.array([[6,1,1],[4,-2,5],[2,8,7]])
res=np.linalg.det(taba)

print(res)

[[ 7  8]
 [31 29]]
[[ 8]
 [26]]
[[0 3]
 [1 4]
 [2 5]]
-306.0
